### ISSUE TITLE
Test Issue

### ISSUE THREAD

**Issue by HMECMAS** [CMASLTD/TEST#1]
Lets see how that works.
![capture](https://cloud.githubusercontent.com/assets/13626516/9040178/37feb92e-39f8-11e5-8ce9-ec44d5c9ae8b.PNG)

**Comment by SMCMAS** [comment]
Test email.

Cheers,
Sasa Milicevic

**Comment by SMCMAS** [comment]
Seems ok, there is a good manual at http://schacon.github.io/git/user-manual.html

**Comment by SMCMAS** [comment]
Seems ok, there is a good manual at http://schacon.github.io/git/user-manual.html

**Comment by HMECMAS** [comment]
Cool. Something for my sleepless nights! :)

**Comment by ECCMAS** [comment]
@ESCMAS @HMECMAS @NACMAS  comments in the issue.
